### ISSUE TITLE
Missing translations for keyword search input

### ISSUE THREAD

**Issue by kamerat** [alfg/opendrinks#1178]
Since #1169 is merged, some already translated languages is missing this key.
The goal of this issue is to track the existing languages that has this key missing to hopefully attract some PR's to patch this.

The file in question: [src/views/KeywordList.vue](https://github.com/alfg/opendrinks/blob/master/src/views/KeywordList.vue)
Key missing translation: `Enter your keyword`.

Please reference this issue in your PR's so I can update the list below.

## FAQ
<details>
   <summary>How do I translate?</summary>
   Inside the i18n element in the code, create a new object with your lang code as a key and an object with trans keys as a value.
   Test to see if it works by running the page locally in a browser that has the language in question as default lang / navigator.language.
</details>
<details>
   <summary>How do I reference to this issue?</summary>
   Simply add "#1178" somewhere in a comment or the PR description.
</details>

## Translation progress
- [ ] ja
- [ ] fr
- [x] es - contributed by @OscarRG #1184
- [x] hi - contributed by @theishanbh #1179
- [ ] gl
- [x] de - contributed by @OscarRG #1183
- [ ] nl
- [x] no - contributed by me #1169
- [x] ru - contributed by @KamaZz #1180
- [x] uk - contributed by @KamaZz #1180
- [x] bn - contributed by @appledora #1181

**Comment by kamerat** [comment]
If you have the time and motivation, feel free to submit a PR;
(People who previously submitted a i18n based PR)
@KamaZz, @appledora, @CharleneHoogkamer, @theishanbh, @DanTcheche, @Xelaflash, @OscarRG, @s-sasaki-0529

**Comment by alfg** [comment]
Awesome. Thanks for this @kamerat.

**Comment by vitorguima** [comment]
@kamerat Ok, I'm working on it and adding portuguese to other parts of the code.

**Comment by rudrakshkarpe** [comment]
I'd like to add English-Marathi Translations if you allow me

**Comment by sykalerio** [comment]
I would like to add Greek translation if you would like to
